version: '3.1'

services:
  nginx:
    build: nginx/
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - kimai:/var/www/kimai:ro
    links:
      - fpm
    restart: always

  fpm:
    build: fpm/
    volumes:
      - kimai:/var/www/kimai
    restart: always

volumes:
  kimai:
    labels:
      - de.felixhummel.project=kimai
