version: '3.7'

services:

  traefik:
    image: traefik:1.7
    command: --api --docker --loglevel=INFO
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:8080:8080

  nginx:
    labels:
      - "traefik.frontend.rule=Host:kimai.s3.localhost"

