version: '3.7'

services:
  nginx:
    build: nginx/
    volumes:
      - html:/etc/nginx/html:ro
    restart: always
    labels:
      - de.felixhummel.project=kimai

  fpm:
    build: fpm/
    environment:
      - KIMAI_PASSWORD_SALT
      - MYSQL_HOSTNAME=mysql
      - MYSQL_DATABASE=kimai
      - MYSQL_USERNAME=kimai
      - MYSQL_PASSWORD=kimai
      - MYSQL_PREFIX=kimai_
      - KIMAI_LANGUAGE=de
      - PHP_TIMEZONE=Europe/Berlin
      - KIMAI_SKIN=standard
    volumes:
      - html:/var/www/html
    restart: always
    labels:
      - de.felixhummel.project=kimai

  mysql:
    build: mysql/
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    labels:
      - de.felixhummel.project=kimai

volumes:
  html:
    labels:
      - de.felixhummel.project=kimai
  mysql_data:
    labels:
      - de.felixhummel.project=kimai
